# Generated by Django 4.1.7 on 2023-03-25 07:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('category', models.CharField(choices=[('Cleaning', 'Уборка'), ('Repair', 'Ремонт'), ('Copywriting', 'Копирайтинг'), ('Food', 'Еда'), ('Cooking', 'Готовка'), ('Delivery', 'Доставка'), ('Other', 'Другое')], default='Other', max_length=50, verbose_name='Категория')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Фото продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000, verbose_name='Отзыв')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=5, message='Значение не может быть более 5'), django.core.validators.MinValueValidator(limit_value=1, message='Значение не может быть менее 1')], verbose_name='Оценка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_product', to='review_app.product', verbose_name='Продукт с отзывом')),
            ],
        ),
    ]
